//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Code
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "代码名称")]
        [Required]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "代码名称长度在2位到20位之间。")]
        public string Name { get; set; }
        [Display(Name = "代码类型")]
        [Required]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "代码类型长度在2位到20位之间。")]
        public string Type { get; set; }
        [Display(Name = "是否可用")]
        [Required]
        public string Memo { get; set; }
    }
}
