//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class ExaminationInformation
    {
        [Key]
        [Required]
        public int Id { get; set; }
        public int StudentId { get; set; }
        [Display(Name = "学科")]
        [Required]
        public int Discipline { get; set; }
        [Display(Name = "考试时间")]
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime ExaminationTime { get; set; }
        [Display(Name = "成绩")]
        [Required]
        [Range(1, 150)]
        public int Fraction { get; set; }

        public virtual StudentInformation StudentInformation { get; set; }
    }
}
